version: '3.4'
services:
  main_reverse_proxy:
      # Notice main_reserve_proxy/install.sh should have been executed before docker-compose!
      image: owge_main_reverse_proxy:${OWGE_CI_VERSION}
      build: main_reverse_proxy/.
      volumes:
        - ${STATIC_IMAGES_DIR}:/var/owge_data/static
        - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
      links:
        - "admin_panel_and_rest_game:owgejava_admin_and_rest_game"
      ports:
        - "${OWGE_PORT}:80"
  admin_panel_and_rest_game:
      image: admin_panel_and_rest_game:${OWGE_CI_VERSION}
      environment:
        - OWGE_REST_WAR_FILENAME
        - CATALINA_OPTS=-Xmx200m -Xms50m -XX:MaxPermSize=64m
      build:
          context: admin_panel_and_rest_game/.
          args:
            - warHolderDirectory=target
            - OWGE_REST_WAR_FILENAME
            - OWGE_UNIVERSE_ID
            - OWGE_DB_URL
            - OWGE_DB_USER
            - OWGE_DB_PASS
      volumes:
          - ${STATIC_IMAGES_DIR}:/var/owge_data/static
          - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
          - /public/owge-data/keys:/var/owge_data/keys
      expose:
          - "8081"

