version: '3.4'

services:
  db:
    build:
      context: ../../../business/database
      dockerfile: ../../docker-ci/dev/images_creation/backend_database/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    expose:
      - "3306"
  rest_and_admin:
    build:
      context: ../../..
      dockerfile: ./docker-ci/dev/images_creation/Dockerfile_for_war_files
      target: game-rest-and-admin
    volumes:
      - ${STATIC_IMAGES_DIR}:/var/owge_data/static
      - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
    ports:
      - "${OWGE_PORT}:8080"
    environment:
      - CATALINA_OPTS=-Dowge.databaseUrl=mysql://db:3306/owge -Dowge.databaseUser=root -Dowge.databasePassword=1234
    links:
      - db:db