version: '3.4'

services:
  db:
    build:
      context: ../../../business/database
      dockerfile: ../../docker-ci/dev/images_creation/backend_database/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    expose:
      - "3306"
  db_mock_account:
    build:
      context: ../../../mock_account/database
      dockerfile: ../../docker-ci/dev/images_creation/mock_account_database/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    expose:
      - "3306"
  rest_and_admin:
    build:
      context: ../../..
      dockerfile: ./docker-ci/dev/images_creation/Dockerfile_for_war_files
      target: game-rest-and-admin
    volumes:
      - ${STATIC_IMAGES_DIR}:/var/owge_data/static
      - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
    ports:
      - "${OWGE_PORT}:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=owge
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - CATALINA_OPTS=-Dowge.databaseUrl=mysql://db:3306/owge -Dowge.databaseUser=root -Dowge.databasePassword=1234
    depends_on:
      - db
  mock_account:
    build:
      context: ../../../mock_account
      dockerfile: ../docker-ci/dev/images_creation/mock_account/Dockerfile
    environment:
      - MYSQL_HOST=db_mock_account
      - MYSQL_DB=owge_account
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports: 
      - "${OWGE_MOCK_ACCOUNT_PORT}:8080"