version: '3.4'

services:
  rest_and_admin:
    build:
      context: ../../..
      dockerfile: ./docker-ci/dev/images_creation/Dockerfile_for_war_files
      target: game-rest-and-admin
    volumes:
      - ${STATIC_IMAGES_DIR}:/var/owge_data/static
      - ${DYNAMIC_IMAGES_DIR}:/var/owge_data/dynamic
    expose:
      - "8080"
    environment:
      - OWGE_CORS_CUSTOM_ORIGIN=*
      - OWGE_DB_URL=db:3306/owge
      - OWGE_DB_USER=root
      - OWGE_DB_PASS=1234
      - MYSQL_HOST=db
      - MYSQL_DB=owge
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234